# -------------------------------------
# Configuration instruction link:
#  https://github.com/xHexed/Oregen3/blob/master/src/main/resources/config.yml
# Please click if you use the plugin the first time or updating
# Notes:
#  generator options:
#    required options: options that MUST be provided, or else the plugin will throw errors
#      random: list of blocks that will randomly be choosen upon generating ores
#    optional options: options that are optionally provided, the generator will work normally if missing
#      permission: the permission it will use instead of the default provided one, default to oregen3.generator.<generator name> if missing
#      fallback: the block it will pick if all other block are not choosen, default to COBBLESTONE if missing
#      sound: sound option that the block will cast if present
#        name: name of the sound, default to BLOCK_FIRE_EXTINGUISH if missing
#        volume: volume of the sound, default to 1 if missing
#        pitch: pitch of the sound, default to 1 if missing
#      world: world-related options
#        blacklist: if the world list provided below are blacklist (non-whitelist), default to true if missing
#        list: list of world that the generator are consider of, default to an empty list if missing
#  enableDependency: it will try to find a skyblock plugin to enable the owner permission feature
#  sound: you can use the old enum sound, as long as it playable in your version (ex: 1.8 sound for 1.12 server)
#  Avalable placeholder for messages:
#  - noPermission: %perm%
#  - noPlayer: %player%
#  - noIslandOthers: %player%
#  - messages:
#     commands: %label% (First argument in command)
#  hooks:
#   Vault:
#    forceAsync: will the plugin force to use the async permission lookup? Change to true if you have problems using the non-async one
#    pluginAsyncList: plugin list that store the permission data async (using database, ...), or you can list other plugins (note that it sometimes won't load before this plugin)
#   BentoBox:
#    gamemodePriorities: (may be changed later)
#     - This plugin will check for avalable gamemode by order. If which addon comes first then it will use that gamemode to check
#       for player's island (who knows someone would use 2 gamemode at a time....)
#     - Since BentoBox lets you install many Gamemodes, this check is required due to the fact this plugin only hooks into one
#       gamemode (may be fixed later).
#     - If an invaild gamemode is found, the plugin will skip it.
# Tips:
#  You can use PlaceholderAPI or MVDWPlaceholderAPI placeholders
#   in every messages (execpt some that requires a player but the message can't get the player's name)
# -------------------------------------
# DO NOT TOUCH THIS
version: 1.3.0.5.1

updater:
  copyHeader: false

mode:
  waterBlock: true
  lavaBlock: false
  waterLava: true

blocks:
- FENCE
- ACACIA_FENCE
- BIRCH_FENCE
- DARK_OAK_FENCE
- IRON_FENCE

enableDependency: true
randomFallback: false
defaultGenerator: default

hooks:
  skyblock:
    getLowestGenerator: false
  Vault:
    forceAsync: false
    pluginAsyncList:
    - LuckPerms
  BentoBox:
    gamemodePriorities:
    - AcidIsland
    - BSkyBlock
    - CaveBlock
    - SkyGrid

global:
  generators:
    world:
      enabled: false
      blacklist: true
      list:
      - world1
      - world2
    sound:
      enabled: false
      name: BLOCK_FIRE_EXTINGUISH
      volume: 3
      pitch: 2

generators:
  default:
    fallback: COBBLESTONE
    random:
      COBBLESTONE: 30.0
      GOLD_BLOCK: 20.0
      IRON_BLOCK: 15.0
      LAPIS_BLOCK: 2.0
    sound:
      name: BLOCK_FIRE_EXTINGUISH
      volume: 3
      pitch: 2
  vip:
    fallback: COBBLESTONE
    permission: test.vip
    priority: 2
    level: 10
    random:
      COBBLESTONE: 30.0
      GOLD_BLOCK: 20.0
      IRON_BLOCK: 15.0
      LAPIS_BLOCK: 2.0
      COAL_BLOCK: 5.0
      REDSTONE_BLOCK: 10.0
    sound:
      name: BLOCK_FIRE_EXTINGUISH
      volume: 3
      pitch: 2
    world:
      blacklist: true
      list:
      - world1
      - world2
  mvp:
    fallback: DIAMOND_ORE
    priority: 3
    level: 10
    random:
      COBBLESTONE: 30.0
      GOLD_BLOCK: 20.0
      IRON_BLOCK: 15.0
      LAPIS_BLOCK: 2.0
      COAL_BLOCK: 5.0
      REDSTONE_BLOCK: 10.0
      DIAMOND_BLOCK: 10.0
      EMERALD_BLOCK: 8.0
    sound:
      name: BLOCK_FIRE_EXTINGUISH
      volume: 3
      pitch: 2
    world:
      blacklist: true
      list:
      - world1
      - world2

messages:
  prefix: '&f[&6OreGen&e3&f]'
  commands:
    help: "&6&o/%label% help &f» Open help pages"
    reload: "&6&o/%label% reload &f» Reload config"
    info: "&6&o/%label% info [player] &f» Getting ore spawning chance of the island you are standing on or the targetted player"
    edit: "&6&o/%label% edit &f» Edit generators in-game (comming soon...)"
  gui:
    title: "&eChances"
    block:
      lore:
      - "&6Chances: &e%chance%&6%"
  noIsland: "&cYou have to be on an island to view this."
  noIslandOthers: "&c%player% have to be on an island to view this."
  missingArgs: "&cMissing arguments"
  noPermission: "&4Missing Permission: &c %perm%"
  noPlayer: "&4Player %player% isn't exist or online"
  notPlayer: "&4Only player can use this command"